dist: xenial
os: linux
services: 
  - docker
language: generic  

before_install:
  - docker build -t statu7/docker-react -f Dockerfile.dev .

script:
  - docker run statu7/docker-react npm run test -- --coverage 

after_failure: "program step was not seccussfully!"
after_success: "all programm steps are successfully! now its time fo deploy!"   


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-2-771724246480"
  bucket_path: "docker-react"
  on:
    branch: master
    