dist: xenial
os: linux
language: ruby
services: 
  - docker

before_install:
  - docker build -t statu7/docker-react -f Dockerfile.dev . 

script:
  -  docker run statu7/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "elasticbeanstalk-us-east-2-771724246480"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_path: "docker-react"
  region: "us-west-2"
  on:
    branch: master

